### ISSUE TITLE
got only "NA"

### ISSUE THREAD

**Issue by yongfeng-zhou** [shenglin-liu/vcf2sfs#1]
Hi,

I tried the vcf2sfs on the gatk vcfs, but I got NA for all analyses. 

source("vcf2sfs.r")
vcf2dadi("whole_PN.recode.vcf","popmap.txt","cult_SNP.sfs",1)

popmap.txt
Autumn_Royal    1
Italia  1
Red_Globe       1
...

result:
25
NA NA NA NA NA NA NA NA NA NA NA NA NA NA NA NA NA NA NA NA NA NA NA NA NA

Thank you!
Yongfeng

**Comment by shenglin-liu** [comment]
Hi Yongfeng,

Thank you for your question!

My script requires that the sample columns of the VCF file start with GT fields. It seems some VCF files generated by GATK do not contain these fields. I have updated my github page and have notified such limitation. I suggest you check your VCF file and see if this is the problem. If that is the case, I'm sorry that my script cannot be applied to your VCF file.

Best regards,
Shenglin

**Comment by shenglin-liu** [comment]
Hi Yongfeng,

If the problem is indeed due to GT fields, you may try this R package (https://github.com/thierrygosselin/radiator/tree/master/R), although it's still under development.

Best,
Shenglin
