### ISSUE TITLE
NA only for 1 population 

### ISSUE THREAD

**Issue by PierreNois** [shenglin-liu/vcf2sfs#2]
Hello,

I used vcf2sfs for SNP data obtained with STACKS and I have no problem with joint sfs but when I tried for one population, I only have NA in the SFS. Where could that come from ?

Thank you,

Pierre

**Comment by shenglin-liu** [comment]
Hi Pierre,

I'm sorry for such a delay in response. I have just updated this github page with a new script. The old one is archived but no longer maintained. Could you try with this new script? It is easier to use than before and much faster. It also gives more functions. I'm sorry if this causes any inconveniences to you. I know how annoying it can be when people upgrade their software or scripts.

Best,
Shenglin

**Comment by PierreNois** [comment]
Thank you for your answer, the update seems nice. I have still some problems with the function vcf2gt that only gives me NA genotype. I join a screen of a part of my data that are, I think, in the right format.

<img width="924" alt="Data format" src="https://user-images.githubusercontent.com/60923166/74522611-cff6f100-4f1b-11ea-9bbb-ba3f3ed7975b.PNG">

**Comment by shenglin-liu** [comment]
Hi Pierre,
Your file seems correct. Here are the suggestions I can think of now.
Could you try opening the file in a text editor, e.g., notepad++, and see if the columns are indeed tab-delimited? You can also view it with less in Linux environment.
Do you by any chance have a variable named "F" in your script? This might cause trouble by confusing with FALSE.
Could you run str to the vcf2gt result and send it to me?
Try running a<-read.table("yourVCF.vcf",sep="\t",stringsAsFactors=F). See if it gives any warnings or error messages.
The last solution would be you send me a fragment of your vcf file and your popmap file. I will try to figure out the problem.

**Comment by PierreNois** [comment]
Hi Shenglin,
Thank you for your help, I could run the script without problem, there was a problem with the metaline of the file.

Have a nice day and thank you again for your support,

Pierre
