### ISSUE TITLE
How to generate folded sfs

### ISSUE THREAD

**Issue by PierreNois** [shenglin-liu/vcf2sfs#3]
Hi Shenglin,

I have a question again, I would like to generate a folded sfs but the function fold.sfs doesn't change my sfs generated with gt2sfs.raw. How could I get a folded sfs ?

Thank you,

Pierre

**Comment by shenglin-liu** [comment]
Hi Pierre,

That is odd. I just ran the script again. It works just fine. Could you plot the SFS (using plot.sfs function) before and after you run fold.sfs and send the plots to me? They should be different.

Best,
Shenglin

**Comment by PierreNois** [comment]
There isn't difference between the two plot. I run this script : 

mygt = vcf2gt("dataC.vcf", "popfile2.txt")
sfsV <-gt2sfs.raw(mygt, "Vosges")
FOLDsfsV = fold.sfs(sfsV)
plot.sfs(sfsV)
plot.sfs(FOLDsfsV)

Do you see any mistakes ?

![unfold](https://user-images.githubusercontent.com/60923166/74647254-a3411480-517b-11ea-97c5-eb623e828308.jpeg). 

![fold](https://user-images.githubusercontent.com/60923166/74647251-a20fe780-517b-11ea-97a9-cd7fa3d88f3b.jpeg)

**Comment by shenglin-liu** [comment]
The script is correct. The plots are also correct. It's just because the bins on the right half of the plot are empty. So the folded SFS is just the same as the unfolded.

Just an extra question. Does Vosges have 93 individuals?

**Comment by PierreNois** [comment]
Yes, there are 93 invidividuals in Vosges

**Comment by shenglin-liu** [comment]
Good!
