### ISSUE TITLE
The generated sfs have more than 2n rows

### ISSUE THREAD

**Issue by Songmh-2020** [shenglin-liu/vcf2sfs#5]
Hi shenglin Liu,

I am using the R script "vcf2sfs" to deal with my data.

I found a problem that is I have 11 samples for one population but I get 57 raws (25 raws are not 0) SFS information for this population. For another population with 9 samples the R script gives 45 raws (18 raws are not 0, that's right).

Can you tell what happeded? 

All the bests,

Meng-Huan Song

**Comment by shenglin-liu** [comment]
Hi Meng-Huan,

There might be some problems with the allele encoding in your VCF file. My script requires that all the SNPs should be biallelic and the alleles should be encoded with "0", "1" and ".". You probably have some alleles encoded with "2", "3" and "4". That would generate SFSs with more than 2n+1 entries.

Best,
Shenglin

**Comment by JavierM88** [comment]
Hi Shenglin-Liu,

I was testing the R functions, and have a question related to the fold.sfs function. Using your examples file I managed to get a raw SFS using:

```
## get gt
gt <- vcf2gt(f.vcf = "example.vcf", f.popmap = "example_popmap.txt")
```

```
## get the 1d SFS for Kap1
sfs_1d <- gt2sfs.raw(gt = gt, pops = "Kap1")
```

```
## folding the SFS
fold.sfs(sfs = sfs_1d)
```

Using `fold.sfs` gives me the same number of entries as the gt2sfs.raw function. I was expecting 0 ... n/2 entries. 

Thank you.

**Comment by shenglin-liu** [comment]
Hi,

Yes, the "fold.sfs" function will generate a SFS with the same length as
the input. There are two main reasons for this. First, when the dimension
of your SFS is >=2, it is impossible to remove the emptied entries after
folding. If you do that, the SFS will no longer have the shape of an array.
Second, in dadi, when you fold a SFS, the number of entries don't change,
either.

Best,
Shenglin
