### ISSUE TITLE
Computing 2D SFS with second population having n=1

### ISSUE THREAD

**Issue by JavierMenRev** [shenglin-liu/vcf2sfs#6]
Hi Shenglin-liu,

I wanted to know if you were planning on implementing an additional function that allows to estimate the 2D SFS when one of the populations has an n=1. Or do you happen to have a quick fix that you've tried already?

Thank you,

Javier

**Comment by shenglin-liu** [comment]
Hi Javier,

Try changing Line 195 from
cnt[,i]<-rowSums(chrom[,index],na.rm=T)
to
cnt[,i]<-rowSums(chrom[,index,drop=FALSE],na.rm=T)

This should do the trick.

Best,
Shenglin

**Comment by JavierMenRev** [comment]
Great, thanks. Yes, that solved it.
Best,
Javier
