### ISSUE TITLE
SFS plot x axis (individuals) starts at 0

### ISSUE THREAD

**Issue by sbreitbart** [shenglin-liu/vcf2sfs#7]
Hi there,

When I perform this function, the resulting table starts at 0. Is this expected? I'm not sure what it would mean for the SFS's x axis (number of individuals) to start at 0. Thanks!

# input
gt2sfs.raw(mygt, "2")

# output
2
   0    1    2    3    4    5    6    7    8    9   10
1461  365  195  108   62   27   18   11    0    3   0

**Comment by shenglin-liu** [comment]
Hi,

Yes, it is expected and is perfectly normal. This category represents
monomorphic nucleotides. In dadi analysis, this category is normally
masked. In fastsimcoal, you actually need to put in an accurate number for
the software to rescale the results. Hope this helps.

Cheers

**Comment by sbreitbart** [comment]
Thanks so much!
